include:
  - template: Terraform/Base.gitlab-ci.yml
  - template: Security/SAST-IaC.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
stages:
  - validate
  - test
  - build
  - deploy
  - cleanup
fmt:
  extends: ".terraform:fmt"
  needs: []
validate:
  extends: ".terraform:validate"
  needs: []
build:
  extends: ".terraform:build"
  environment:
    name: "mattermost-sfo3"
    action: prepare
deploy:
  extends: ".terraform:deploy"
  dependencies:
    - build
  environment:
    name: "mattermost-sfo3"
    action: start
